### ISSUE TITLE
Materialise #enhancement

### ISSUE THREAD

**Issue by demil133** [urandom/gearshift#26]
Three small points:
 * Red round add button. 
 * Gray-ish notification bar. 
 * List separator don't fill the whole width.

If I have some spare time I'll look into it myself. It's just makeup for an already great app.

**Comment by urandom** [comment]
Adding a torrent is definitely not the main action of the list activity, that's why there's no FAB. Adding a torrent through the app itself is most likely one of lesser used actions, since its much easier to add torrents via intents (via clicks from other apps).

The notification bar color is transparent, You really can't make it any more gray-ish than that, since it depends on the toolbar color.

**Comment by demil133** [comment]
True, I very rarely add torrents through the app itself
