### ISSUE TITLE
Don't push server settings

### ISSUE THREAD

**Issue by rb07** [urandom/gearshift#38]
Currently the app is pushing the server settings it has, no matter what the current settings at the server are, no matter if the user changed a setting or not.

What is expected is that the app preserves the daemon (actually any Tranmission client) settings.  The app should be reading those settings from the server (to show the actual values), and only send them when the user makes a change (that's what Transmission-qt with a remote session does).

**Comment by urandom** [comment]
The first requests to the server are always for a fresh session (server settings) and the current list of torrents. If you change some session variable (through the server settings, for example), the updated session is sent back to the daemon. What it does with it is entirely up to it and out of the hands of any one client. I remember that older versions of the daemon only retained the session changes while it was active (i.e. until the daemon was restarted). They might have changed that behavior now.

**Comment by rb07** [comment]
I disagree, the daemon doesn't loose its settings, or change them on restart (but many people doesn't know how to actually configure the daemon on their systems, so it may appear that it does when in fact is something in /etc/defaults or /etc/conf.d, but that is off-topic).

You say "the first request", but that is not clear: 1st after the app starts, or 1st after the app resumes operation (in Android all apps are kept "running", all the time, until you actually re-boot the device, or kill the app).

I'm sure the app (version 1.0 from the "About" panel, but I think that is wrong, its actually 1.0.1 if I remember correctly, the time-stamp on the apk is July, 12) is pushing the settings because I changed them (through Transmission-qt w/remote session), and after some time they would revert, and the only thing that could make them revert, other than restarting the daemon with different defaults, is your app which, by the way, was showing the old setting (so it never read the new from the server).

**Comment by urandom** [comment]
The only time the session is pushed to the daemon is when you change something in the remote settings screen, or toggle the alt speed mode. And only the changed keys are pushed, not the whole thing.

> You say "the first request", but that is not clear: 1st after the app starts, or 1st after the app resumes operation (in Android all apps are kept "running", all the time, until you actually re-boot the device, or kill the app).

Pretty sure everyone who's ever written a hello world android app knows that :)
What I meant by that statement that from a cold start, the first thing that's done is fetch the new session, since old values are stored in sqlite and if they were somehow sent to the daemon, newer configuration might be overwritten.. The session is also updated on every 3rd request, so its reasonably fresh all the time.

Now, since you seem to have a very good way of reproducing this problem, I suggest you enable the debug logging from the settings. The output will get quite verbose, but at least you'll know when and how the app is communicating with the daemon. It might turn out to really be a bug.
