### ISSUE TITLE
Torrent detail screen changes if the torrent displayed disappears from the selection in the main screen

### ISSUE THREAD

**Issue by subiol** [urandom/gearshift#53]
Basically the title, torrent detail screen changes if the torrent displayed disappears from the selection in the main screen.

An example, in the main torrent screen I am filtering by Active, so I get a list of the active torrents. Now I click in one, and I get to the torrent detail screen for that specific torrent. While I am checking the torrent detail screen, if the selected torrent becomes inactive and is then removed from the main screen list, it is also removed from the torrent detail screen and the details of a different torrent that is active are shown instead.

What I would expect is, if I select to view the torrent details of a specific torrent, I keep seeing the details of that specific torrent, even when it is removed from the present selection.

**Comment by urandom** [comment]
I won't be fixing this in the current version. The details page is a giant viewpager, which uses the same source as the list itself. If I ever finish rewriting the app, I don't plan on using a viewpager for the details (just a single instance to whatever torrent as clicked), so that problem be present.
