### ISSUE TITLE
How about making a widget?

### ISSUE THREAD

**Issue by makenb** [urandom/gearshift#60]
It would be awesome to have a widget to track downloads!

**Comment by urandom** [comment]
I've recently had the 'pleasure' of investigating how widgets are created for another app. Unfortunately, the widget api is extremely simple, and tailored towards uses that do not require frequent updates.

A potential widget would have to update itself infrequently (think at least 15 minutes if you value your battery life), since there is no way to have frequent updates _only_ while the widget is visible. Thus, there would have to be a manual refresh button, which kind of defeats the purpose for me.

**Comment by makenb** [comment]
Thank you for the explanation! I like your app anyway!
